Feature/add camera2
Banuba/quickstart-android-c-api pull request #8
Opened 2022-07-22 11:28 UTC by sdk-banuba

2022-07-22 12:05 UTC, dmitrystoyanovsky requested changes

2022-07-22 12:05 UTC, dmitrystoyanovsky commented on app/src/main/java/com/banuba/quickstart_c_api/MainActivity.java
> +    private ByteBuffer imageToByteBuffer(Image image) {
imageToByteBuffer - unused, remove

2022-07-22 12:05 UTC, dmitrystoyanovsky commented on app/src/main/cpp/native-lib.cpp
> +        }
I guess here should be assert, to let user immediately to know that not all formats are supported in the sample

2022-07-22 12:05 UTC, dmitrystoyanovsky commented on app/src/main/cpp/native-lib.cpp
> -        banuba_sdk_manager(const std::vector<std::string>& path_to_resources, const std::string& client_token)
Please return this back and fix code assuming that manager is manager

2022-07-22 12:11 UTC, dmitrystoyanovsky requested changes

2022-07-22 12:11 UTC, dmitrystoyanovsky commented on app/src/main/cpp/native-lib.cpp
>              /* Create an instance of effect_player implementation with cpp api, pass path to location of
fix comment

2022-07-26 07:58 UTC, dmitrystoyanovsky requested changes

2022-07-26 07:58 UTC, dmitrystoyanovsky commented on README.md
> +5. Configure effect in the appropriate section of `com/banuba/quickstart_c_api/MainActivity.java`, e.g. effects/test_BG The effects folder should be located in the `app/src/main/assets/` folder. More
Please make sure that you have .gitkeep file to let the folder `app/src/main/assets/` exist as a part of repo. Also changes in this folder should be ignored by git.

2022-07-26 07:58 UTC, dmitrystoyanovsky commented on app/src/main/cpp/native-lib.cpp
> +        assert(format == bnb::oep::interfaces::image_format::nv12_bt601_full);
Please add BT601 i420 format - we need to compare perf NV12 vs i420

2022-07-26 07:58 UTC, dmitrystoyanovsky commented on app/src/main/java/com/banuba/quickstart_c_api/GLNVRenderer.java
> +package com.banuba.quickstart_c_api;
rename the file to GLYUVNVRenderer, if you add the swap colors option then your renderer will support also NV21 format - it is the same as NV12 but bytes in UV plane are swapped, else please name file GLYUVNV12Renderer.

2022-07-26 07:58 UTC, dmitrystoyanovsky commented on app/src/main/java/com/banuba/quickstart_c_api/GLNVRenderer.java
> +                        "float Umax = 0.436; \n" +
Make sure that you use the right coefficients for conversion - better pass them as a uniform matrix.

2022-07-26 07:58 UTC, dmitrystoyanovsky commented on app/src/main/java/com/banuba/quickstart_c_api/GLNVRenderer.java
> +        GLES20.glActiveTexture(GLES20.GL_TEXTURE0);
you can refactor it to the loop

2022-08-03 06:56 UTC, sdk-banuba commented on app/src/main/java/com/banuba/quickstart_c_api/rendering/GLRGBARenderer.java
> +    public void makeVBO() {
Это должно быть в базовом классе в конструкторе

2022-08-03 06:56 UTC, sdk-banuba commented on app/src/main/java/com/banuba/quickstart_c_api/rendering/GLRGBARenderer.java
> +    public void makeTextures() {
Должно быть в базовом классе:
textures = new int[5];
createTextures(textures);
deleteTextures(textures);

2022-08-03 06:56 UTC, sdk-banuba commented on app/src/main/java/com/banuba/quickstart_c_api/rendering/GLRGBARenderer.java
> +        GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT);
в базовом классе создай методы:
prepareDrawing()
draw()
finishDrawing()

Желательно что бы в классах наследниках не было вызовов OpenGL напрямую.

2022-08-03 06:56 UTC, sdk-banuba commented on app/src/main/java/com/banuba/quickstart_c_api/rendering/GLRenderer.java
> +
лишние отступы

2022-08-03 06:56 UTC, sdk-banuba commented on app/src/main/java/com/banuba/quickstart_c_api/rendering/GLNV12Renderer.java
> +                    "precision mediump float;\n" +
отступы. Не должно так быть

2022-08-03 07:11 UTC, sdk-banuba commented on app/src/main/cpp/native-lib.cpp
> +        banuba_sdk_manager()
banuba_sdk_manager(int32_t width, int32_t height)

2022-08-03 07:11 UTC, sdk-banuba commented on app/src/main/cpp/native-lib.cpp
> +            auto ep = bnb::oep::interfaces::effect_player::create(1, 1);
width, height instead of 1, 1

2022-08-03 07:11 UTC, sdk-banuba commented on app/src/main/java/com/banuba/quickstart_c_api/OffscreenEffectPlayer.java
> +class ImageInfo {
Это должен быть отдельный java класс.
Назови его OffscreenEffectPlayerImage. В него будут передаваться плейны.
3 конструктора минимум.
для RGBA для NV12 и для I420

2022-08-03 07:11 UTC, sdk-banuba commented on app/src/main/java/com/banuba/quickstart_c_api/OffscreenEffectPlayer.java
> +    public void processImageAsync(ByteBuffer imageY, ByteBuffer imageU, ByteBuffer imageV, ImageInfo info) {
void processImageAsync(OffscreenEffectPlayerImage image)

2022-08-03 12:37 UTC, dmitrystoyanovsky approved these changes
Let us make a task to fix comments (tech debt) and right now proceed with the required measurements.

2022-08-04 06:14 UTC, PiotrBanuba approved these changes

2022-08-04 07:54 UTC, merged